export const USER_REPOS_REQUEST = 'USER_REPOS_REQUEST';
export const USER_REPOS_RESPONSE = 'USER_REPOS_RESPONSE';
export const USER_REPOS_FAILED = 'USER_REPOS_FAILED';

export const CHANGE_SORT_FIELD = 'CHANGE_SORT_FIELD';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_CURRENT_REPO = 'CHANGE_CURRENT_REPO';
